development: &global_settings
  host: localhost
  database: ***REMOVED***-final
  port: 27017


test:
  database: marv-test
  <<: *global_settings

production:
  host: localhost
  database: setilive-dev
  port: 27017

