development: &global_settings
  host: localhost
  database: ***REMOVED***
  port: 27017


test:
  database: marv-test
  <<: *global_settings

production:
  host: ***REMOVED***
  database: ***REMOVED***
  port: 27188
  username: setilive
  password: ***REMOVED***

