development: &global_settings
  host: localhost
  database: marv
  port: 27017

test:
  database: marv-test
  <<: *global_settings

production:
  host: mongodb.setilive.org
  database: ***REMOVED***
  port: 27188
  username: setilive
  password: ***REMOVED***


