development: &global_settings
  host: localhost
  database: marv
  port: 27017

test:
  database: marv-test
  <<: *global_settings

production:
  host: arrow.mongohq.com
  database: setilive
  port: 27017
  username: stuartlynn
  password: astr0Talk_#!
  <<: *global_settings