development: &global_settings
  host: localhost
  database: setilive-production
  port: 27017


test:
  database: marv-test
  <<: *global_settings

production:
  host: MONGO_HOST
  database: MONGO_DATABASE
  port: MONGO_PORT
  username: MONGO_USERNAME
  password: MONGO_PASSWORD
