development:
  host: localhost
  thread_safe: true
  port: 6379
  db: 10
  
test:
  host: localhost
  thread_safe: true
  port: 6379
  db: 1

production:
  host: 127.0.0.1
  thread_safe: true
  port: 6379
  password: ***REMOVED***