development:
  host: localhost
  thread_safe: true
  port: 6379
  db: 10
  
test:
  host: localhost
  thread_safe: true
  port: 6379
  db: 1

production:
  host: ***REMOVED***
  thread_safe: true
  password: ***REMOVED***
  port: 6381