development:
  host: localhost
  thread_safe: true
  port: 6379
  db: 10
  
test:
  host: localhost
  thread_safe: true
  port: 6379
  db: 1

production:
  host: REDIS_HOST
  thread_safe: true
  password: REDIS_PASSWORD
  port: REDIS_PORT